name: Create CLI Release

on:
  workflow_dispatch:
    inputs:
      isStableCandidate:
        type: boolean
        description: Is this a stable/prod candidate?
        required: true
        default: false
  workflow_call:
    inputs:
      isStableCandidate:
        type: boolean
        description: Is this a stable/prod candidate?
        required: true
        default: false

jobs:
  get-version-channel:
    runs-on: ubuntu-latest
    outputs:
      channel: ${{ steps.getVersion.outputs.channel }}
      version: ${{ steps.getVersion.outputs.version }}
      # final check to ensure package.json doesn't have a dist tag, ex: '-beta'
      isStableRelease: ${{ fromJSON(inputs.isStableCandidate) && !steps.getVersion.outputs.channel }}
    steps:
      - uses: actions/checkout@v3
      - id: getVersion
        uses: ./.github/actions/get-version-and-channel/
        with:
          path: './packages/cli/package.json'
  
  get-release-sha:
    needs: [get-version-channel]
    runs-on: ubuntu-latest
    outputs:
      release-sha: ${{ steps.getSha.outputs.SHA }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - name: get release sha
        id: getSha
        run: |
          SHA=$(npm view heroku@${{ needs.get-version-channel.outputs.version }} --json | jq -r '.gitHead[0:7]')
          echo $SHA >> $GITHUB_OUTPUT

  publish-npm:
    needs: [get-version-channel]
    # if NOT isStableCandidate confirm dist tag is in package.json version
    if: fromJSON(needs.get-version-channel.outputs.isStableRelease) || (!fromJSON(inputs.isStableCandidate) && !!needs.get-version-channel.outputs.channel)
    uses: ./.github/workflows/publish-npm.yml
    with:
      isStableRelease: ${{ fromJSON(needs.get-version-channel.outputs.isStableRelease) }}
      channel: ${{ needs.get-version-channel.outputs.channel }}
    secrets: inherit

  pack-upload:
    needs: [ publish-npm ]
    uses: ./.github/workflows/pack-upload.yml
    secrets: inherit

  promote:
    needs: [get-version-channel, pack-upload]
    if: needs.pack-upload.result == 'success'
    uses: ./.github/workflows/promote-release.yml
    with:
      version: ${{ needs.get-version-channel.outputs.version }}
      isStableRelease: ${{ fromJSON(needs.get-version-channel.outputs.isStableRelease) }}
      channel: ${{ needs.get-version-channel.outputs.channel }}
    secrets: inherit
  
  upload-to-stampy:
    needs: [get-version-channel, get-release-sha, promote]
    name: Upload windows installer to Stampy
    uses: "./.github/workflows/stampy-upload.yml"
    with:
      sha: ${{ needs.get-release-sha.outputs.release-sha }}
      version: ${{ needs.get-version-channel.outputs.version }}
